service: amirotate
provider:
  name: aws
  runtime: nodejs4.3
  region: ${env:AWS_REGION}
  timeout: 300
  memorySize: 256
  environment:
    tagKey: amirotate
  iamRoleStatements:
  - Effect: Allow
    Action:
    - ec2:CreateImage
    - ec2:CreateTags
    - ec2:DeleteSnapshot
    - ec2:DeregisterImage
    - ec2:DescribeImages
    - ec2:DescribeInstances
    - ec2:DescribeSnapshots
    - ec2:DescribeTags
    Resource: "*"
plugins:
- serverless-webpack
functions:
  create:
    handler: create.default
    events:
    - schedule:
        rate: cron(0 0 ? * * *)
        # input:
        #   tagKey: amirotate # You can override tag key here
  delete:
    handler: delete.default
    events:
    - schedule:
        rate: cron(0 1 ? * * *)
